# Example from https://docs.docker.com/reference/compose-file/build/#additional_contexts
# Added actually executable RUN commands
services:
  base:
    build:
      context: .
      dockerfile_inline: |
        # using the latest official image from https://hub.docker.com/_/alpine
        FROM alpine
        RUN echo -en "\e[92mThis file is from the base service's image.\e[0m\n" > ~/a-file.txt
  my-service:
    build:
      context: .
      dockerfile_inline: |
        FROM base
        RUN echo -en "\e[93mMeanwhile, here's a file created during the my-service service's image build.\e[0m\n" > ~/another-file.txt
      additional_contexts:
        base: service:base
